### ISSUE TITLE
Library directory not accessible

### ISSUE THREAD

**Issue by maxmahlke** [jghauser/papis.nvim#3] opened 2022-10-08 17:14 UTC
First, congrats on this nice plugin and the extensive documentation you provide! It gives a good impression of what the plugin provides and its extensive config options.

I'm having trouble getting started. I set the config as explained in the readme:

```
papis_python = {
  dir = "/home/max/astro/papers",
  info_name = "info.yaml",
  notes_name = [[notes.org]],
}
```

yet when I run `:PapisStart` I get the following output:

```
/home/max/~/astro/papers/ is not accessible by the current user!                                                 
/home/max/~/astro/papers/ is not accessible by the current user!                                                 
Press ENTER or type command to continue   
```

I tried different values for `dir`: `~/astro/papers/`,  `astro/papers/`, `astro/papers`, always the same message. The directory exists and is accessible to my user. Just to make sure it's the directory that the variable requires, it is the directory which contains my papers:

```
~ ❯ ls ~/astro/papers | head -3
0023fdcfceb1927113193f3bba1c3a80-marchi-s-and-lazzar
006e027d026931904dbe4c331f2a79b4-levison-harold-f.-a
0188fb24dfc019dd6986c965ef4dd07f-fedkin-a.-v.-and
```

**Comment by jghauser** [comment] 2022-10-08 17:21
It looks like there's something fishy going on with the `~`. Though I don't quite understand what as I have `/home/julian/Documents/library/main` in my config and it works without issues.

Does it also fail if you leave the config empty (papis.nvim then queries papis for the config values)?

I'll investigate this further later today.

**Comment by jghauser** [comment] 2022-10-08 17:23
What OS are you on?

**Comment by maxmahlke** [comment] 2022-10-08 18:21
I'm on Linux, pop-os. Leaving the config empty does not lead to an error but running `:Telescope papis` in that case provides me with zero options.

**Comment by jghauser** [comment] 2022-10-08 18:49
Ok, thanks so much for helping debug this!

Did this error:
```
/home/max/~/astro/papers/ is not accessible by the current user!                                                 
/home/max/~/astro/papers/ is not accessible by the current user!                                                 
Press ENTER or type command to continue   
```
happen with the above config? Or when `dir` was set to `~/astro/papers/`? If with the above config, then I'm a bit confused how that tilde got in there haha. If it wasn't with the above config, can you try again with `/home/max/astro/papers` (as in your above config) and send me the error message?

What might also help is to enable debug mode and send me the logs. There's instructions in the README.

**Comment by maxmahlke** [comment] 2022-10-08 21:37
This message

```
/home/max/~/astro/papers/ is not accessible by the current user!
```

appeared with all different `dir` values I give in the first post. I spent some time looking into this now: I deleted the `papis-nvim.sqlite3` file from the cache, after which the message vanished. I then started to see some papers appear in the `:Telescope papis` call, and I got a notification of a missing `ref: ` entry in a paper. There are apparently numerous cases of this in my library, not sure why I never noticed this. [Side note: I made sure using `stat` that these files were not modified since I installed your plugin, confirming what you say in the readme, the `info.yaml` is not touched.]

As I'm fixing the missing references, the list of papers in the database grows, cool.

Now, I'd like to give you the debug info, but enabling the debug module does not work for me. I added it to the config (opening a PR about a missing comma in a second) yet 

```
newconf["enable_modules"]["debug"]
```

remains `False`. I disabled `impatient.nvim` and put the `papis.nvim` setup call at the end of my `init.lua`, no success, the debug commands are not available.

I'll keep investigating. I'm now suspecting that this error is on my side, I'll keep you updated.

**Comment by jghauser** [comment] 2022-10-08 22:05
This is how I found out that some `ref` fields were missing in my library too... ;)

And I should have thought of the database being in a funny state. I think similar things happened to me when changing the `dir` value. I think the `PapisReInitData` command might have fixed it (if it was available). In general, I guess we should handle this more gracefully... I'll think about how!

About debug. This is again something I can't seem to reproduce. In my config I have:
```lua
enable_modules = {
	["debug"] = true,
},
```
And this does the trick. :thinking: Do keep me updated. Otherwise if you could share a minimal config, I could try replicate things on my end.

**Comment by maxmahlke** [comment] 2022-10-10 19:00
After adding the missing `ref`entries and removing the cached `papis-nvim.sqlite3` database, I can now select articles using `:Telescope papis` and insert their citations! It's a bit slow for the size of the database (738 articles) but I suspect that's on my telescope side.

A new issue is that the user commands throw errors, e.g. running `:PapisOpenNote` gives:

```
Error executing Lua callback: ...m/site/pack/packer/opt/papis.nvim/lua/papis/commands.lua:63: attempt to call field 'open_note' (a nil value)
stack traceback:
        ...m/site/pack/packer/opt/papis.nvim/lua/papis/commands.lua:63: in function <...m/site/pack/packer/opt/papis.nvim/lua/papis/commands.lua:62>
```

`:PapisOpenFile` and `:PapisEditEntry` give the analogous errors, it's the commands from the `papis.commands` module only. The debug commands work fine.

I think that this is just a symptom of the actual, yet to be discovered issue, much like the first one I reported was due to the malformed SQL database, which was due to missing `ref` entries. I'll close this one and open another if I'm able to figure out what's going wrong now. Stay tuned ;-)

**Comment by jghauser** [comment] 2022-10-10 19:14
Glad to hear the first thing got sorted out!

Yeah, searching is a bit slow. My library is about double your size and searching isn't as smooth as I would want though also not so slow that i have to consciously wait for results. I haven't yet figured out how to speed things up. That's definitely on my todo list.

About the error. I get that too! I hadn't noticed because I always use the keymaps, and they're not affected. This should be an easy fix, gimme a couple of minutes! Thanks for reporting :)

**Comment by jghauser** [comment] 2022-10-10 19:24
Ok, should be fixed now! Let me know if not and keep the bugs coming :)

**Closed by jghauser** 2022-10-10 19:24 UTC

**Comment by maxmahlke** [comment] 2022-10-11 10:04
Can confirm that it works now! And +1 for speeding up the search, I will look into it as well, though I don't know much about the sqlite backend.

**Comment by jghauser** [comment] 2022-10-11 14:43
The speed issue probably doesn't have to do with the sqlite backend. I've opened #8, happy to hear your feedback!
